site_name: راهنمای شاززز
extra_css:
  - stylesheets/Shabnam/shabnam.css
  - stylesheets/extra.css
theme:
  name: material
  language: fa
  logo: 
    assets/shaazzz.png
  font:
    text: Shabnam
  favicon:
    assets/shaazzz.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/shaazzz
    - icon: fontawesome/solid/globe
      link: https://shaazzz.ir
    - icon: fontawesome/brands/github
      link: https://github.com/shaazzz
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright:
  این راهنما عمومی است و تحت پروانه <a href="https://pdcommunity.ir/license/cc-by-sa" style="color:blue">cc-by-sa</a> در دسترس است.

