site_name: راهنمای شاززز


theme:
  name: material
  language: fa
  logo: 
    assets/shaazzz.png
  favicon:
    assets/shaazzz.png
  font:
    text: Shabnam
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/shaazzz
    - icon: fontawesome/solid/globe
      link: https://shaazzz.ir
    - icon: fontawesome/brands/github
      link: https://github.com/shaazzz
repo_url: https://github.com/MEgooneh/shaazzz-guide

copyright:
  این راهنما عمومی است و تحت پروانه <a href="https://pdcommunity.ir/license/cc-by-sa" style="color:blue">cc-by-sa</a> در دسترس است.
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

